### ISSUE TITLE
Related objects are not updated propertly

### ISSUE THREAD

**Issue by gregquat** [algolia/AlgoliaSearchBundle#17]
Hi,

I have some problem with updates. Let's take this object :

{ 'user': 
    'firstname' : 'john',
    'lastname' : 'doe',
    'address' : {
        'city': 'Paris',
        'number': 123
    }
}

I want to index "firstname", "lastname" (with an autoIndex on User). I also index this method :

getStringAddress() { return $this->getAddress()->getNumber().' '.$this->getAddress()->getCity();}

but with no autoIndex on Address.

When I create a new object, everythings looks fine. I can retrieve all my fields.

When I update only the firstname, sometimes it looks fine (firstname updated, other fields still here), other times not (firstname updated, other fields disappeared). 

When I update the city, in the better case, my object is not updated but still here (here = indexed in the algolia system). In the worst case, all the fields have disappeared.

My analysis is that this method should be bugged (https://github.com/algolia/AlgoliaSearchBundle/blob/master/Indexer/Indexer.php#L229). The line 238 should work in every case (put this line at 232 fixes the problem as the update is now considered at a creation) whereas the 236 does not do the job. This is probably due to the use of the getEntityChangeSet() method (https://github.com/algolia/AlgoliaSearchBundle/blob/master/EventListener/AlgoliaSearchDoctrineEventSubscriber.php#L61) that seems to not take care of related objects.

This analysis explains why the object is not updated when I only update a field on a related object. but it does not explain why some data are removed from the index sometimes...

I wish you luck! :)

**Comment by maxiloc** [comment]
@gregquat Thanks. Yes I already planned to remove this creation/update separation, will be available soon

**Comment by gregquat** [comment]
@maxiloc Great, thanks. I haven't done the PR since I do not understand very well you internal behaviour and I was afraid to do some mistake.

**Comment by fabientsr** [comment]
Hi,

I just tested this fix and the problem isn’t fully corrected.

The related object is updated only in the case of the main object is updated.
And even if the main object is updated, the others haven’t the update...

**Comment by maxiloc** [comment]
We need to check if there is a way to go back to the parent to update it in case of a update on the relation

**Comment by maxiloc** [comment]
@fabientsr I didn't find a way to automatically do that. What I would recommend is to use manual indexing after updating the relashionship like this

```
$this->get('algolia.indexer')->getManualIndexer($em)->index($related->mainObject());
```

ps: I am open to suggestions if someone has a better way to handle this case

**Comment by fabientsr** [comment]
Ok. Thanks.

**Comment by chriwup** [comment]
@maxiloc : will the manual indexer check the IndexIf property first before indexing or do we have to check it manually before calling index() ?

**Comment by maxiloc** [comment]
@chriwup Yes the check is supposed to be done even with manual indexer

**Comment by chriwup** [comment]
We've implemented our own fix for this kind of problem, here's how it works if others have the same issue:
- created an interface that expects a getObjectsToIndex() function
- all classes related to the main one need to implement this interface, and return the "mappedBy" property
- a subscriber class called on the doctrine postUpdate event : it processes only entities that implement our interface and calls the manual indexer with objects returned by getObjectsToIndex

**Comment by gregquat** [comment]
Hi, It seems I still have this kind of problem.
The original problem was "when I change an entity property, the children entities are not updated". I think it's fixed now.
Now, it seems I have this problem : when I update a children entity, the change is not """always""" propagated to Algolia.
I'm not 100% sure of that but I made some tests.

If I take back my example above, I have a user and an address. My DB and Algolia are synchronised, all is fine.
But if I only change the address, the new address is flushed in DB, but not synchronised to Algolia (still the former one).
There is no autoIndex, only @Algolia\Attribute annotations on $user->address and $address->city.

I'm going to work on this on Thurday and dive into the AlgoliaSearchBundle source code to find if something is wrong.

If you have any clue, or things to tell me before, it would be helpfull and kind :)
Thanks

**Comment by maxiloc** [comment]
@gregquat Yes that is one of the limitation of orms not only doctrine. When you update a child entity it's not triggering an event for the parent.
So you need to trigger the indexing manually with:
```
$this->get('algolia.indexer')->getManualIndexer($em)->index($related->mainObject());
```

**Comment by chriwup** [comment]
@gregquat you'll need to implement what I described in my comment above if you want to make it maintainable and easy to add new objects.
